### ISSUE TITLE
npx ts-node open_browser.ts Fails to grab Patreon cookies.

### ISSUE THREAD

**Issue by Toxic-Cookie** [rksm/patreon-scraper#6]
So I run "```npx ts-node open_browser.ts```", log in to patreon, close the window and the console says done.

However, running "```npx ts-node open_browser.ts --check-cookies```" makes the console say undefined and then done.

Trying to run "```npx ts-node ./fetch_data.ts --campaign_id 1682532 --data_dir darknetdiaries_data --patreon_url https://www.patreon.com/darknetdiaries/```" Fails due to: ```Error: no session_id cookie found! at run (C:\Users\user\source\repos\patreon-scraper\fetch_data.ts:114:11) at processTicksAndRejections (internal/process/task_queues.js:93:5)```

If possible could we just get a simple config file to enter a username and password into instead? The cookie thing seems pretty brittle.

**Comment by Toxic-Cookie** [comment]
This is on Windows 10 by the way. I've been following the guide at https://robert.kra.hn/posts/2019-11-29_patreon-scraper/ and I had to improvise the step at running ```npx ts-node open_browser.ts``` by manually copying the User Data folder for chrome in my appdata and pasting it into the directory it wants or the browser window won't open at all due to ```Error: Chrome user data dir not found at 'C:\Users\user\source\repos\patreon-scraper\user_data'``` I almost made it to the end but I'm just stuck on this issue which I think the code will need to be modified in order to work.

**Comment by rksm** [comment]
Yeah sorry, I don't think this will work on windows.
