### ISSUE TITLE
Error's due to addition of captcha

### ISSUE THREAD

**Issue by jmeachum** [rksm/patreon-scraper#7]
I received the following error:
`/Users/username/code/patreon-scraper/fetch_data.ts:78
        const data = JSON.parse(rawData) as PostData;`

I then added a console log output of the rawData to see what was going on and got the following:
`got session_id DRAnFiwLv8jPA48pyqxQBMXJY887drF_lGb15GlhPY8
<html><head><title>patreon.com</title><script src="/cdn-cgi/apps/head/7F2Ggij0e_TCnVgy3dJ0eOuIIUs.js"></script><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMAUjDKu30UrI4AaLO9zA==','hsh':'DAA83DD4A3D06098A6A2CE2AD90A76','t':'fe','s':37896,'host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>`

**Comment by dtk1985** [comment]
same error for me. i don't know how to check the console log but the first part is the same.

**Comment by rksm** [comment]
Yeah I'm looking into that. I think it is possible to work around this as requests in the context of the web page still work fine.
